// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJsZu7zbNhueTbhbHaC8U3KiDmZzSdOaM',
    appId: '1:313873147970:web:4a9f089d210b587ca6a5db',
    messagingSenderId: '313873147970',
    projectId: 'notekeeper-b48a5',
    authDomain: 'notekeeper-b48a5.firebaseapp.com',
    storageBucket: 'notekeeper-b48a5.appspot.com',
    measurementId: 'G-TNG06EJYR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV-nXkihkNmoFJwJN0Nz_v03GveSSQUWM',
    appId: '1:313873147970:android:3538e81d929f26baa6a5db',
    messagingSenderId: '313873147970',
    projectId: 'notekeeper-b48a5',
    storageBucket: 'notekeeper-b48a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoGBS6Tnz5Cx8j3gpx6JwqLXyJuEwAy4Y',
    appId: '1:313873147970:ios:e67a5d6c8b85aac6a6a5db',
    messagingSenderId: '313873147970',
    projectId: 'notekeeper-b48a5',
    storageBucket: 'notekeeper-b48a5.appspot.com',
    iosClientId: '313873147970-ut1fmomk51059nl996haismpde0or4m0.apps.googleusercontent.com',
    iosBundleId: 'com.example.notekeeper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoGBS6Tnz5Cx8j3gpx6JwqLXyJuEwAy4Y',
    appId: '1:313873147970:ios:e67a5d6c8b85aac6a6a5db',
    messagingSenderId: '313873147970',
    projectId: 'notekeeper-b48a5',
    storageBucket: 'notekeeper-b48a5.appspot.com',
    iosClientId: '313873147970-ut1fmomk51059nl996haismpde0or4m0.apps.googleusercontent.com',
    iosBundleId: 'com.example.notekeeper',
  );
}
